from typing import Protocol


class RecursoGestionable(Protocol):
    def validar(self) -> None: ...
    def reconciliar(self, device: "Device") -> dict: ...
    def aplicar(self, device: "Device") -> dict: ...
    def repositorio(self) -> str: ...
