from typing import Protocol


class RecursoGestionable(Protocol):
    def validar(self) -> None: ...
    def reconciliar(self, device: "Device") -> dict: ...
    def aplicar(self, device: "Device", pre_state: "dict | None" = None) -> dict: ...
    def repositorio(self) -> str: ...
